### ISSUE TITLE
umap-learn 0.4.4 breaks dimRed UMAP embedding

### ISSUE THREAD

**Issue by pujxxukndo** [gdkrmr/dimRed#51] opened 2020-06-11 10:33 UTC
Code example (from the `dimRed` documentation):
```r
> dat <- loadDataSet("3D S Curve", n = 300)
> umap <- UMAP()
> emb <- umap@fun(dat, umap@stdpars)
Warning message:
In detect.umap.learn(config) :
  cannot recognize umap-learn version 0.4.4; set umap_learn_args manually
> emb2 <- embed(dat, "UMAP", .mute = NULL, knn = 10)
Warning message:
In detect.umap.learn(config) :
  cannot recognize umap-learn version 0.4.4; set umap_learn_args manually
```
The latest `umap-learn` was installed as recommended (`conda install -c conda-forge umap-learn`).

Session info:
```r
R version 4.0.1 (2020-06-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.9.0
LAPACK: /usr/lib/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8    LC_NUMERIC=C            LC_TIME=en_AG           LC_COLLATE=en_US.UTF-8 
 [5] LC_MONETARY=en_AG       LC_MESSAGES=en_US.UTF-8 LC_PAPER=en_AG          LC_NAME=C              
 [9] LC_ADDRESS=C            LC_TELEPHONE=C          LC_MEASUREMENT=en_AG    LC_IDENTIFICATION=C    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dimRed_0.2.3   DRR_0.0.4      CVST_0.2-2     Matrix_1.2-18  kernlab_0.9-29

loaded via a namespace (and not attached):
 [1] umap_0.2.5.0    Rcpp_1.0.4.6    cluster_2.1.0   magrittr_1.5    splines_4.0.1   MASS_7.3-51.6  
 [7] rappdirs_0.3.1  lattice_0.20-41 tools_4.0.1     parallel_4.0.1  grid_4.0.1      packrat_0.5.0  
[13] nlme_3.1-148    mgcv_1.8-31     vegan_2.5-6     RSpectra_0.16-0 askpass_1.1     openssl_1.4.1  
[19] permute_0.9-5   compiler_4.0.1  reticulate_1.16 jsonlite_1.6.1
```

**Comment by gdkrmr** [comment] 2020-06-14 14:46
The issue is that `umap` (the `R` package) doesn't work with the new version of `umap-learn`. See the source code of `umap:::detect.umap.learn`. This is already fixed in the `umap` repo: https://github.com/tkonopka/umap/commit/d99c1a4834651d1c308bc0d1d5cc6157a77197ea and I guess that it will work again when it gets published on CRAN.

Until then: could try installing the develop version of `umap` and see if this fixes things? It would be great if you could report back here. I currently have a machine running Ubuntu 16.04 and cannot install the latest `umap-learn` (the `python` package)  because of an outdated llvm dependency (and  currently no time to tinker with this).

**Comment by pujxxukndo** [comment] 2020-06-15 06:51
I can confirm that installing `umap` from the master branch fixes this issue!

**Comment by gdkrmr** [comment] 2020-06-15 07:45
Thanks! I'll leave this open until the new release of `umap`.

**Comment by gdkrmr** [comment] 2021-12-07 09:40
This is fixed now, but R `umap` is not compatible with python `umap-learn` 0.5 and the author probably won't fix it (https://github.com/tkonopka/umap/issues/14). I have added a comment to the documentation but long term we should probably switch to R `uwot` or just use`reticulate`.

**Closed by gdkrmr** 2021-12-07 09:40 UTC
Labels: upstream
